#!/bin/bash

# run smartctl on all physical disks
#
# Usage: smrtctl [ short | long | none ]
#
# - default is short
# - requires smartctl command, and diskutil (on macOS) or lsblk (on Linux)
#
# v0.1 (May 2021) by Andrew Davis (addavis@gmail.com)

# 1 optional arg: short or long (default short)
test=short

if (( $# == 1 )) \
    && [[ "$1" == short || "$1" == long || "$1" == none ]]
then
    test=$1
    shift

elif (( $# > 0 ))
then
    echo >&2 "optional command: short (default), long, or none (i.e. only turn on smart)"
    exit 2
fi

disks=()
if [[ -n $( command -v diskutil ) ]]
then
    # macOS
    mapfile -t disks < <( diskutil list physical | cut -d ' ' -f 1 )

elif [[ -n $( command -v lsblk ) ]]
then
    # linux
    mapfile -t disks < <( lsblk -pnd -o NAME,TYPE | grep ' disk$' | cut -d ' ' -f 1 )

else
    echo >&2 "did not find disk listing command"
    exit 3
fi

(( ${#disks[*]} > 0 )) \
    || { echo >&2 "did not find any disks"; exit 4; }

# iterate over all physical disks and start the test
for d in "${disks[@]}"
do
    # ignore info lines
    [[ $d == ' ' ]] && continue

    sc_args=( -s on )

    if [[ $test != none ]]
    then
        echo >&2 "smrtctl: Running $test smart selftest on $d"
        sc_args+=( -t "$test" )

    else
        echo >&2 "smrtctl: Turning on smart for $d"
    fi

    command smartctl "${sc_args[@]}" $d \
        || break

    sleep 2  # don't overwhelm the system
done
