# aliases to the compgen-match function
alias ls-aliases='compgen-match alias'
alias ls-arrays='compgen-match arrayvar'
alias ls-bindings='compgen-match binding'
alias ls-builtins='compgen-match builtin'
alias ls-cmds='compgen-match command'
alias ls-exports='compgen-match export'
alias ls-funcs='compgen-match function'
alias ls-helptopics='compgen-match helptopic'
alias ls-jobs='compgen-match job'
alias ls-keywords='compgen-match keyword'
alias ls-setopts='compgen-match setopt'
alias ls-shopts='compgen-match shopt'
alias ls-signals='compgen-match signal'
alias ls-vars='compgen-match variable'
